spring.application.name=userService
# Thông tin kết nối MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/userservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update # Tự động cập nhật schema khi ứng dụng khởi động
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

