# spring:
#   application:
#     name: meetingservice
#   datasource:
#     url: jdbc:mysql://localhost:3306/meetingservice
#     username: root
#     password: 123qwe
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#     open-in-view: false
#   kafka:
#     consumer:
#       bootstrap-servers: localhost:9092  # Địa chỉ Kafka server
#       group-id: notification-group              # ID nhóm của consumer
#       auto-offset-reset: earliest       # Đặt lại offset khi không tìm thấy dữ liệu
#       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#       value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#     producer:
#       bootstrap-servers: localhost:9092  # Địa chỉ Kafka server
#       key-serializer: org.apache.kafka.common.serialization.StringSerializer
#       value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.164:8761/eureka/
  instance:
    prefer-ip-address: true  # THÊM DÒNG NÀY
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  # TÙY CHỌN


  