server:
  port: 8081

spring:
  application:
    name: notificationservice

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.0.37:8761/eureka/  # IP máy chủ Eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}